image: maven:3-jdk-10

cache:
  paths:
    - .m2/repository
    - target/

stages:
- build

DiceMobManager:
  stage: build
  script:
     - mvn verify
  artifacts:
     paths:
     - target/DiceMobManager.jar
  only:
    - master

