image: maven:3.5.3-jdk-8

cache:
  paths:
    - .m2/repository/
    - target/

deploy:
  stage: deploy
  script:
     - mvn verify
  artifacts:
     paths:
     - target/DiceMobManager.jar
  only:
    - master
