image: maven:3.5.3-jdk-8

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn compile
  only:
    - master    

test:
  stage: test
  script:
    - mvn test
  only:
    - master

deploy:
  stage: deploy
  script:
     - mvn verify
  artifacts:
     paths:
     - target/DiceMobManager.jar
  only:
    - master
