name: DiceMobManager
main: de.dicecraft.dicemobmanager.DiceMobManager
version: "1.0"
author: Walkehorst Lukas
authors: []
website: http://dicecraft.de
api-version: "1.16"
commands:
  MobManager:
    description: Base Command of the MobManager
    permission: dicemobmanager
    usage: /<command> [command]